version: '3.8'

services:
  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django
    build:
      context: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - '8001:8000'
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./app
    volumes:
      - ./app:/usr/src/app/
    env_file:
      - .env


